# Generated by GPT-5.2 on 2026-02-14

from decimal import Decimal

from django.db import migrations


def seed_products(apps, schema_editor):
    ProductCategory = apps.get_model("products", "ProductCategory")
    Product = apps.get_model("products", "Product")

    categories = [
        {
            "name": "Одежда",
            "description": "Толстовки, футболки и другая одежда.",
        },
        {
            "name": "Обувь",
            "description": "Кроссовки и другая обувь.",
        },
        {
            "name": "Аксессуары",
            "description": "Сумки, кепки и другие аксессуары.",
        },
    ]

    category_by_name = {}
    for c in categories:
        category, _ = ProductCategory.objects.get_or_create(
            name=c["name"], defaults={"description": c["description"]}
        )
        category_by_name[c["name"]] = category

    products = [
        {
            "name": "Adidas Hoodie",
            "category": "Одежда",
            "description": "Утеплённая худи на каждый день.",
            "price": Decimal("2390.00"),
            "quantity": 15,
        },
        {
            "name": "Nike T‑Shirt",
            "category": "Одежда",
            "description": "Базовая хлопковая футболка.",
            "price": Decimal("990.00"),
            "quantity": 40,
        },
        {
            "name": "Puma Joggers",
            "category": "Одежда",
            "description": "Удобные джоггеры для прогулок и тренировок.",
            "price": Decimal("1790.00"),
            "quantity": 25,
        },
        {
            "name": "Adidas Sneakers",
            "category": "Обувь",
            "description": "Лёгкие кроссовки для города.",
            "price": Decimal("4990.00"),
            "quantity": 12,
        },
        {
            "name": "New Balance 574",
            "category": "Обувь",
            "description": "Классическая модель на каждый день.",
            "price": Decimal("6990.00"),
            "quantity": 10,
        },
        {
            "name": "Cap",
            "category": "Аксессуары",
            "description": "Кепка с регулировкой размера.",
            "price": Decimal("790.00"),
            "quantity": 50,
        },
        {
            "name": "Gym Bag",
            "category": "Аксессуары",
            "description": "Сумка для тренировок и поездок.",
            "price": Decimal("1290.00"),
            "quantity": 20,
        },
    ]

    for p in products:
        Product.objects.update_or_create(
            name=p["name"],
            defaults={
                "description": p["description"],
                "price": p["price"],
                "quantity": p["quantity"],
                "category": category_by_name[p["category"]],
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_basket"),
    ]

    operations = [
        migrations.RunPython(seed_products, reverse_code=migrations.RunPython.noop),
    ]

